### ISSUE TITLE
Improvement: Use textarea instead of text field

### ISSUE THREAD

**Issue by 0dB** [0dB/cats-utils#1]
I think I would need help by @sharkdp, the author of `purescript-flare`, for this:

* to add a foreign function that creates a textarea component or
* to let me know how to do it with almost zero knowledge of JavaScript.

**Comment by sharkdp** [comment]
That should be possible. I'd be best if you could open an issue in the purescript-flare repository.

**Comment by 0dB** [comment]
Solved via purescript-flare 3.1.0 (thanks!).
